#!/bin/sh

while getopts u:t: name
do
	case $name in
	u) user=$OPTARG;;
	t) table=$OPTARG;;
	esac
done

if [ -z "$user" ]; then
	user="root"
fi

if [ -z "$table" ]; then
	echo "must -t option."
	exit 0;
fi

mysql -u $user -p -e "drop database if exists ${table}; create database ${table} default character set utf8"
