#!/bin/sh

while getopts u:d:h: name
do
	case $name in
	u) user=$OPTARG;;
	d) dbname=$OPTARG;;
	h) host=$OPTARG;;
	esac
done

if [ -z "$user" ]; then
	user="root"
fi

if [ -z "$host" ]; then
	host="localhost"
fi

if [ -z "$dbname" ]; then
	echo "must -d option."
	exit 0;
fi

mysql -u $user -p -h $host -e "drop database if exists ${dbname}; create database ${dbname} default character set utf8"
